
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = 'ABA129A04250926751015271926E874A'
    
_lr_action_items = {'SEMICOLON':([5,],[6,]),'NUMBER':([4,],[5,]),'OP_EQUAL':([3,],[4,]),'VAR':([0,],[1,]),'ID':([1,],[3,]),'$end':([2,6,],[0,-1,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'define':([0,],[2,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> define","S'",1,None,None,None),
  ('define -> VAR ID OP_EQUAL NUMBER SEMICOLON','define',5,'p_define','parser.py',6),
]
